### ISSUE TITLE
Probléme de variables?

### ISSUE THREAD

**Issue by ghost** [Leowrin/Arduino-Airplane#9]
Tes variables : 
byte Pitch;
byte RightA;
etc....

sont des byte et tu veux que ça soit égale à des String.

Du coup c'est normal ou pas ? Si c'est normal , alors il te manque une fonction pour faire ça. Sinon faut corriger.

<3 Avec amitié

**Comment by Leowrin** [comment]
J'ai corrigé, j'avais oublié de convertir les Strings. C'est la ligne 45 qui fait la conversion.
